name: Build Container Image

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v3.4.0
      with:
        images: ghcr.io/lexfrei/vk2tg/vk2tg
        tags: |
          type=sha
          type=ref,event=branch

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.2.0

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push
      uses: docker/build-push-action@v2.5.0
      if: github.ref == 'refs/heads/main'
      with:
        context: .
        file: ./build/vk2tg/Dockerfile
        platforms: linux/amd64, linux/arm64
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}

    - name: Build
      uses: docker/build-push-action@v2.5.0
      if: github.ref == !'refs/heads/main'
      with:
        context: .
        file: ./build/exporter/Dockerfile
        platforms: linux/amd64, linux/arm64
        tags: ${{ steps.docker_meta.outputs.tags }}

